sudo: false
cache: bundler
language: ruby
matrix:
  include:
     - rvm: jruby-9.0.1.0
       env: JRUBY_OPTS='--debug' # get more accurate coverage data
     - rvm: 2.0.0
     - rvm: 2.1.10
     - rvm: 2.2.6
     - rvm: 2.3.3
     - rvm: 2.4.0
     - rvm: ruby-head
     - rvm: rbx-3
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
  fast_finish: true
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
  # Running YARD under jruby crashes so skip checking manual under jruby
  - ruby -e "exit 1 unless RUBY_PLATFORM == 'java'" || bundle exec rake generate_cops_documentation
addons:
  code_climate:
    repo_token: a11b66bfbb1acdf220d5cb317b2e945a986fd85adebe29a76d411ad6d74ec31f
