# These are all the cops that are disabled in the default configuration.

Style/AutoResourceCleanup:
  Description: 'Suggests the usage of an auto resource cleanup version of a method (if available).'
  Enabled: false

Style/CollectionMethods:
  Description: 'Preferred collection methods.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size'
  Enabled: false

Style/Copyright:
  Description: 'Include a copyright notice in each file before any code.'
  Enabled: false

Style/Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#utf-8'
  Enabled: false

Style/InlineComment:
  Description: 'Avoid inline comments.'
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Description: 'Avoid chaining a method call on a do...end block.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#single-line-blocks'
  Enabled: false

Style/MissingElse:
  Description: >-
                Require if/case expressions to have an else branches.
                If enabled, it is recommended that
                Style/UnlessElse and Style/EmptyElse be enabled.
                This will conflict with Style/EmptyElse if
                Style/EmptyElse is configured to style "both"
  Enabled: false
  EnforcedStyle: both
  SupportedStyles:
    # if - warn when an if expression is missing an else branch
    # case - warn when a case expression is misisng an else branch
    # both - warn when an if or case expression is missing an else branch
    - if
    - case
    - both

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-i'
  Enabled: false

Style/ExtraSpacing:
  Description: 'Do not use unnecessary spacing.'
  Enabled: false

Lint/LiteralInInterpolation:
  Description: 'Avoid interpolating literals in strings'
  AutoCorrect: false
