name: Unmark issues and pull requests as stale on activity
on:
  issue_comment:
    types: [created]

# actions/stale does this automatically, but only once a day.
# This immediately removes the label when the user creates a comment.
jobs:
  remove-stale-label:
    if: (github.repository == 'rubocop/rubocop')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Remove stale label
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh issue edit ${{ github.event.issue.number }} --remove-label "stale" -R ${{ github.repository }}
